package suckhttp

type Headers []string

const (
	Accept                    = "accept"
	Accept_Charset            = "accept-charset"
	Accept_Encoding           = "accept-encoding"
	Accept_Language           = "accept-language"
	Accept_Ranges             = "accept-ranges"
	Authorization             = "authorization"
	Allow                     = "allow"
	Age                       = "age"
	Cache_Control             = "cache-control"
	Connection                = "connection"
	Content_Encoding          = "content-encoding"
	Content_Language          = "content-language"
	Content_Length            = "content-length"
	Content_Range             = "content-range"
	Content_Type              = "content-type"
	Content_Disposition       = "content-disposition"
	Cookie                    = "cookie"
	DNT                       = "dnt"
	Date                      = "date"
	ETag                      = "etag"
	Expect                    = "expect"
	Expires                   = "expires"
	Host                      = "host"
	If_Modified_Since         = "if-modified-since"
	If_Range                  = "if-range"
	If_None_Match             = "If-None-Match"
	Last_Modified             = "last-modified"
	Location                  = "location"
	Origin                    = "origin"
	Pragma                    = "pragma"
	Range                     = "range"
	Referer                   = "referer"
	Server                    = "server"
	Set_Cookie                = "set-cookie"
	TE                        = "te"
	Trailer                   = "trailer"
	Transfer_Encoding         = "transfer-encoding"
	User_Agent                = "user-agent"
	Vary                      = "vary"
	Via                       = "via"
	Upgrade_Insecure_Requests = "upgrade-insecure-requests"
)
